config/routes.rb
Favratio::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :favs

  resources :tweets

  resources :twitter_users

  match 'twitter_users/:id/refresh_from_twitter' => 'twitter_users#refresh_from_twitter'
  match 'twitter_users/:id/crawl' => 'twitter_users#crawl', as: "crawl_twitter_user"

  root :to => 'twitter_users#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_many :favs
  belongs_to :author, class_name: "TwitterUser"

  validates_length_of :text, :maximum => 140
  validates_presence_of :author_id, :text
  validates_uniqueness_of :twitter_uid

  def inspect
    "#{text}"
  end
end

# == Schema Information
#
# Table name: tweets
#
#  id                :integer          not null, primary key
#  twitter_uid       :string(255)
#  text              :text
#  author_id         :integer
#  timestamp         :datetime
#  is_atreply        :boolean
#  fav_count         :integer
#  fav_weight        :float
#  favs_per_follower :float
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  -if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  %div.field
    = f.label :text
    = f.text_area :text

  .actions
    = f.submit 'Save'

app/views/tweets/_tweet.html.haml
.tweet{id: "#{@tweet.twitter_uid}"}
  = image_tag(@tweet.author.avatar_url,
              class: "avatar",
              alt: @tweet.author.twitter_username,
              title: @tweet.author.twitter_username)
  %p#text
    = h @tweet.text

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
%h1 Listing tweets

%table
  %tr
    %th
    %th
    %th
    %th
    %th

  - @tweets.each do |tweet|
    %tr
      %td= h tweet.text
      %td= tweet.author.twitter_username
      %td= link_to 'Show', tweet
      %td= link_to 'Edit', edit_tweet_path(tweet)
      %td= link_to 'Destroy', tweet, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

= render 'tweet'

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path