config/routes.rb
Favratio::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :favs

  resources :tweets

  resources :twitter_users

  match 'twitter_users/:id/refresh_from_twitter' => 'twitter_users#refresh_from_twitter'
  match 'twitter_users/:id/crawl' => 'twitter_users#crawl', as: "crawl_twitter_user"

  root :to => 'twitter_users#index'

end

app/models/fav.rb
class Fav < ActiveRecord::Base
  attr_accessible :tweet_id, :faver_id
  belongs_to :tweet
  belongs_to :faver, class_name: "TwitterUser"

  validates_presence_of :tweet_id, :faver_id
  validates_uniqueness_of :faver_id, :scope => :tweet_id

  def to_s
    "#{tweet_id} faved by #{faver.twitter_username}"
  end
end

# == Schema Information
#
# Table name: favs
#
#  id         :integer          not null, primary key
#  tweet_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  faver_id   :integer
#

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  # GET /favs
  # GET /favs.json
  def index
    @favs = Fav.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favs }
    end
  end

  # GET /favs/1
  # GET /favs/1.json
  def show
    @fav = Fav.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fav }
    end
  end

  # GET /favs/new
  # GET /favs/new.json
  def new
    @fav = Fav.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fav }
    end
  end

  # GET /favs/1/edit
  def edit
    @fav = Fav.find(params[:id])
  end

  # POST /favs
  # POST /favs.json
  def create
    @fav = Fav.new(params[:fav])

    respond_to do |format|
      if @fav.save
        format.html { redirect_to @fav, notice: 'Fav was successfully created.' }
        format.json { render json: @fav, status: :created, location: @fav }
      else
        format.html { render action: "new" }
        format.json { render json: @fav.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /favs/1
  # PUT /favs/1.json
  def update
    @fav = Fav.find(params[:id])

    respond_to do |format|
      if @fav.update_attributes(params[:fav])
        format.html { redirect_to @fav, notice: 'Fav was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fav.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favs/1
  # DELETE /favs/1.json
  def destroy
    @fav = Fav.find(params[:id])
    @fav.destroy

    respond_to do |format|
      format.html { redirect_to favs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/views/favs/_form.html.haml
= form_for @fav do |f|
  -if @fav.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fav.errors.count, "error")} prohibited this fav from being saved:"
      %ul
        - @fav.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tweet_id
    = f.number_field :tweet_id
  .actions
    = f.submit 'Save'

app/views/favs/edit.html.haml
%h1 Editing fav

= render 'form'

= link_to 'Show', @fav
\|
= link_to 'Back', favs_path

app/views/favs/index.html.haml
%h1 Listing favs

%table
  %tr
    %th Tweet
    %th
    %th
    %th

  - @favs.each do |fav|
    %tr
      %td= fav.tweet_id
      %td= link_to 'Show', fav
      %td= link_to 'Edit', edit_fav_path(fav)
      %td= link_to 'Destroy', fav, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Fav', new_fav_path

app/views/favs/new.html.haml
%h1 New fav

= render 'form'

= link_to 'Back', favs_path

app/views/favs/show.html.haml
%p#notice= notice

%p
  %b Tweet:
  = @fav.tweet_id

= link_to 'Edit', edit_fav_path(@fav)
\|
= link_to 'Back', favs_path